[tool.poetry]
name = "dndbot"
version = "0.1.0"
description = ""
authors = ["Jaydon Schumacker"]

[tool.poetry.dependencies]
python = "^3.8"
discord = "^1.0.1"
credentials = "^1.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
